version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  s3-local:
    image: localstack/localstack:latest
    container_name: s3-local
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=localhost
      - USE_SSL=false
      - DEBUG=1

volumes:
  db-data:
    driver: local
